# code: language=ansible

# Set of tasks for creating a secret in a namespace
# for storing S3 based backups when auth is password
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Secret for S3
  tags: ['target', 'secret', 'smoketest']
  block:
    - name: Configure the secret yaml
      ansible.builtin.template:
        src: templates/secrets.yaml.j2
        dest: /tmp/secrets.yaml
        mode: "0600"
      register: trilio_kubernetes_secret

    - name: Create the secret used by the S3 target in the namespace {{ trilio_kubernetes_namespace }}
      when: trilio_kubernetes_auth_type == 'password'
      kubernetes.core.k8s:
        api_key: "{{ trilio_kubernetes_auth_results.k8s_auth.api_key }}"
        kind: Secret
        state: present
        namespace: "{{ trilio_kubernetes_namespace }}"
        validate_certs: false
        src: /tmp/secrets.yaml
      register: trilio_kubernetes_secret

    - name: Remove temporary secret yaml
      when: trilio_kubernetes_target_type | lower == "s3"
      ansible.builtin.file:
        path: /tmp/secrets.yaml
        state: absent
