# code: language=ansible

# Set of tasks for deploying an app from a YAML source file
# to a namespace specifed
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Namespace
  ansible.builtin.include_tasks: trilio_kubernetes_create_ns.yaml
  tags: ['namespace', 'smoketest', 'deploy_app']

- name: Deploy Application
  tags: ['deploy_app', 'smoketest']
  when: trilio_kubernetes_deploy_demo_app | bool
  block:
      - name: Create App in {{ trilio_kubernetes_namespace }}
        kubernetes.core.k8s:
            state: present
            namespace: "{{ trilio_kubernetes_namespace }}"
            validate_certs: false
            src: "{{ trilio_kubernetes_demo_app_yaml }}"
            wait: true
        register: trilio_kubernetes_app_deployment

      - name: Application Deployment in the namespace {{ trilio_kubernetes_namespace }}
        when:
            - trilio_kubernetes_auth_type == "kubeconfig"
            - trilio_kubernetes_cli | bool
        ansible.builtin.shell: >
          kubectl get po,pvc,svc -n {{ trilio_kubernetes_namespace }}
        environment:
            KUBECONFIG: "{{ kubeconfig }}"
        register: trilio_kubernetes_deployment_available
        ignore_errors: true

      - name: Application Deployment in the namespace {{ trilio_kubernetes_namespace }}
        when:
            - trilio_kubernetes_auth_type == "external"
            - trilio_kubernetes_cli | bool
        ansible.builtin.command: >
          kubectl get po,pvc,svc -n {{ trilio_kubernetes_namespace }}
        register: trilio_kubernetes_deployment_available
        ignore_errors: true

      - name: Show backup created output
        ansible.builtin.debug:
            var: trilio_kubernetes_deployment_available.stdout_lines
