# code: language=ansible
# Unified tasks for creating a secret in a namespace

- name: Configure the secret yaml
  ansible.builtin.template:
    src: templates/secrets.yaml.j2
    dest: /tmp/secrets.yaml
    mode: "0600"
  register: trilio_kubernetes_secret

- name: Create the secret used by the S3 target in the namespace {{ trilio_kubernetes_namespace_var }}
  kubernetes.core.k8s:
    kind: Secret
    state: present
    namespace: "{{ trilio_kubernetes_namespace_var }}"
    validate_certs: "{{ k8s_validate_certs }}"
    api_key: "{{ k8s_auth_api_key }}"
    host: "{{ k8s_auth_host }}"
    src: /tmp/secrets.yaml
  register: trilio_kubernetes_secret

- name: Remove temporary secret yaml
  when: trilio_kubernetes_target_type | lower == "s3"
  ansible.builtin.file:
    path: /tmp/secrets.yaml
    state: absent
