- name: Set Auth Facts
  ansible.builtin.include_tasks: "trilio_kubernetes_common_auth.yaml"
  tags: ['always']

- name: Deploy Application
  tags: ['deploy_app', 'smoketest']
  ansible.builtin.include_tasks: "trilio_kubernetes_deploy_app_tasks.yaml"
  when:
    - trilio_kubernetes_deploy_demo_app | bool
  vars:
    trilio_kubernetes_namespace_var: "{{ trilio_kubernetes_namespace }}"
