galaxy_info:
  author: Kevin Jackson
  description: Ansible role to orchestrate backup, recovery and migration of Kubernetes applications and data using Trilio.
  company: Trilio
  license: Apache-2.0
  min_ansible_version: "2.17"
  platforms:
    - name: GenericUNIX
      versions:
        - all
  galaxy_tags:
    - kubernetes
    - backup
    - restore
    - dataprotection
    - migration

dependencies: []
